services:
  - type: web
    name: drugs-mart-pos
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn pos.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: ADMIN_USERNAME
        value: "admin"
      - key: ADMIN_PASSWORD
        value: "admin123"
      - key: CASHIER_USERNAME
        value: "cashier1"
      - key: CASHIER_PASSWORD
        value: "cashier123"
