# Generated by Django 6.0.2 on 2026-03-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_product_image_alter_employee_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesagent',
            name='total_commision_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
