# Generated by Django 6.0.2 on 2026-03-06 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_salesagent_total_commision_earned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesagent',
            old_name='total_commision_earned',
            new_name='total_commission_earned',
        ),
    ]
