# Generated by Django 6.0.2 on 2026-03-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_total_commision_earned_salesagent_total_commission_earned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesagent',
            name='total_commission_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
