# Generated by Django 6.0.2 on 2026-03-07 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_salesagent_total_commission_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentplan',
            name='credit_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.creditofficer'),
        ),
    ]
