# Generated by Django 6.0.2 on 2026-03-19 14:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_orderitem_cost_price_product_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contract_expiration',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='contract_start',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('Renewed', 'Renewed'), ('Opted Out', 'Opted Out'), ('Active', 'Active'), ('Expired', 'Expired')], default='Active', max_length=100),
        ),
    ]
