# Generated by Django 6.0.2 on 2026-03-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_supplier_contract_expiration_supplier_contract_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Andriod', 'Andriod'), ('iPhone', 'iPhone'), ('Printer', 'Printer')], default='Laptop', max_length=100),
        ),
    ]
