# Generated by Django 6.0.2 on 2026-03-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Android', 'Android'), ('iPhone', 'iPhone'), ('Printer', 'Printer')], default='Laptop', max_length=100),
        ),
    ]
