# Generated by Django 6.0.2 on 2026-03-23 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_employee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditofficer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='creditofficer',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounts.employee'),
        ),
    ]
