# Generated by Django 6.0.2 on 2026-03-23 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_creditofficer_is_active_alter_creditofficer_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditofficer',
            name='employee',
            field=models.OneToOneField(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='accounts.employee'),
        ),
    ]
