# Generated by Django 6.0.2 on 2026-03-23 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_invoice_order_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesagent',
            name='employee',
            field=models.OneToOneField(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='accounts.employee'),
        ),
    ]
