# Generated by Django 6.0.2 on 2026-03-23 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_salesagent_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchinventory',
            name='branch',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='accounts.branch'),
        ),
    ]
