# Generated by Django 6.0.2 on 2026-03-24 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_customer_is_active_alter_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyClaims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(choices=[('Repair', 'Repair'), ('Replacement', 'Replacement')], default='Repair', max_length=20)),
                ('faulty_serial', models.CharField(max_length=100)),
                ('issue_description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed'), ('Released', 'Released')], default='Pending', max_length=20)),
                ('date_filed', models.DateTimeField(auto_now_add=True)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_claims', to='accounts.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='ReplacementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_serial', models.CharField(max_length=100)),
                ('new_serial', models.CharField(max_length=100)),
                ('replacement_date', models.DateTimeField(auto_now_add=True)),
                ('warranty_claims', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.warrantyclaims')),
            ],
        ),
    ]
