# Generated by Django 6.0.2 on 2026-03-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_warrantyclaims_replacementrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantyclaims',
            name='cost_impact',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
