# Generated by Django 6.0.2 on 2026-03-26 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_warrantyclaims_cost_impact'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectiveInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faulty_serial', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('is_disposed', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.product')),
            ],
        ),
    ]
