# Generated by Django 6.0.2 on 2026-03-31 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_defectiveinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchinventory',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
