# Generated by Django 6.0.2 on 2026-03-31 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_branchinventory_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchinventory',
            options={'ordering': ['-date_added']},
        ),
    ]
