# Generated by Django 6.0.2 on 2026-04-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_branchinventory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
