# Generated by Django 6.0.2 on 2026-04-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_employee_is_logged_in_employee_last_login_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
