# Generated by Django 6.0.2 on 2026-04-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_employee_last_logout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_logged_out',
            field=models.BooleanField(default=True),
        ),
    ]
