# Generated by Django 6.0.2 on 2026-04-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_employee_is_logged_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_logged_out',
        ),
    ]
