# Generated by Django 5.2.1 on 2026-08-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_audittrail_id_alter_branch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Cashier', 'Cashier'), ('Sales Agent', 'Sales Agent'), ('Pharmacist', 'Pharmacist'), ('Credit Officer', 'Credit Officer'), ('Inventory Manager', 'Inventory Manager'), ('Manager', 'Manager')], default='Sales Agent', max_length=100),
        ),
    ]
