# Generated by Django 5.2.1 on 2026-08-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.FloatField(default=31.5204),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.FloatField(default=74.3587),
        ),
    ]
